# Generated by Django 3.1 on 2022-04-10 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_diaryqueryset'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiaryQuerySet',
        ),
    ]
