# Generated by Django 3.1 on 2022-04-16 04:54

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_delete_diaryqueryset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='text',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
