# Generated by Django 3.1 on 2022-04-17 06:20

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20220416_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='text',
            field=markdownx.models.MarkdownxField(verbose_name='本文'),
        ),
    ]
