# Generated by Django 3.1 on 2022-04-18 07:48

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20220417_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='text',
            field=markdownx.models.MarkdownxField(help_text='Markdown形式で書いてください', verbose_name='本文'),
        ),
    ]
